//данные получила с помощью фильтрации
export const brandOptions = [
    "Baraka",
    "Piaget",
    "Jacob & Co",
    "Cartier",
    "Bibigi",
    "Van Cleef & Arpels",
    "Pomellato",
    "Bvlgari",
    "Pasquale Bruni",
    "ЭПЛ Якутские бриллианты",
    "Chopard",
    "Casato",
    "Imma",
    "Faberge",
    "Roberto Coin",
    "Damiani",
    "Carrera y Carrera",
    "De Beers",
    "Audemars Piguet",
    "Mikimoto",
    "Giorgio Visconti",
    "Stephen Webster",
    "Chaumet",
    "Tiffany & Co",
    "Franck Muller",
    "De Grisogono",
    "Mauboussin",
    "Casa Gi",
    "Alfieri & St.John"
];
